[package]
name = "purl-driver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "format"
path = "src/format.rs"

[[bin]]
name = "parse"
path = "src/parse.rs"

[dependencies]
purl = { path = "repo/purl" }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
