name: Generate and publish

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
          submodules: recursive
      - name: Build
        run: |
          python3 -m venv env
          . env/bin/activate
          pip install -r requirements.txt
          python -m survey.build
          mkdir dist
          python -m survey.suite > dist/test-suite-report.json
          cp -r site/* dist
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
